version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:1.21-alpine
    # container_name: '${APP_NAME}-nginx'
    container_name: nginx
    ports:
      - '8088:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - pgsql
    networks:
      - laravel

  pgsql:
    image: postgres:14.2-alpine
    # container_name: '${APP_NAME}-pgsql'
    container_name: pgsql
    restart: unless-stopped
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/pgsql
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - '9000:9000'
    networks:
      - laravel
